### ISSUE TITLE
sig_float:  Implement scientific() function

### ISSUE THREAD

**Issue by steph1111** [steph1111/PRECISE#2]
Given a sig_float object, converts the numerical output to scientific notation

**Comment by schrodinstein** [comment]
Might it be easier to create separate code for scientific?

**Comment by steph1111** [comment]
Maybe?? Honestly I am not sure on this one. Ive been trying to figure out a clean way to do `scientific()` for a while now and cant figure it out, if you have any suggestions I am open to anything

**Comment by steph1111** [comment]
Decided to discard the scientific() public function and add it as a feature to latex. Seems to be working well tho
