### ISSUE TITLE
sig_float: Overline significant digit

### ISSUE THREAD

**Issue by steph1111** [steph1111/PRECISE#27]
Reassigning the internal string with the number that has the overlined zero, unsure if this is gonna contribute to problems

**Comment by steph1111** [comment]
As cisco how this should work
```python
num1 = sig_float("55")
num2 = sig_float("55")
num3 = sig_float("1.0")
num4 = sig_float("1.0")
print(RED + f"3) {num1} * {num2} * {num3} + {num4} = {num1 * num2 * num3 + num4}" + GREEN) # Should be overlined
```
```
12) 55  * 55  * 1.0  + 1.0  = 3000 
````

**Comment by steph1111** [comment]
Overlining causing issues, reassess functionality

**Comment by steph1111** [comment]
May want to implicate this in a latex format rather than ascii??
 0.00\bar{0}8723

**Comment by schrodinstein** [comment]
Yes, probably best to format it in Latex. Unicode can get spicy.

**Comment by steph1111** [comment]
At the moment I have it working both ways, in which internally its store as an overlined zero in unicode but in the latex() function it is replaced with the latex equivalent. Seems to be working well. Only issue is I am still having trouble implicating it for addition and subtraction
