### ISSUE TITLE
sig_float: Add .latex() function to format the numbers

### ISSUE THREAD

**Issue by steph1111** [steph1111/PRECISE#30]

**Comment by steph1111** [comment]
See discussion

**Comment by schrodinstein** [comment]
[Replied](https://github.com/steph1111/PERCISE/discussions/18#discussioncomment-5786698)

**Comment by steph1111** [comment]
This is working well 
```0.08206 \; L \cdot atm \cdot mol^{-1} \cdot K^{-1}```

**Comment by steph1111** [comment]
Units in the denominator but not numerator:
f = sig_float("300.0", {"s":-1})
300.0\frac{}{s}

**Comment by steph1111** [comment]
```python
f = sig_float("300.0", {"s":-1})
print(f.latex(format=2))
print(f.latex(format=1))
```
```
300.0 \frac {1}{s}
300.0 \; s^{-1}
```

**Comment by steph1111** [comment]
Updated implicated of latex(), It works well now
