### ISSUE TITLE
This protect needs a license 

### ISSUE THREAD

**Issue by steph1111** [steph1111/PRECISE#37]
See: [creativecommons](https://creativecommons.org/licenses/)

### Attribution-NonCommercial-ShareAlike
CC BY-NC-SA

### Attribution-ShareAlike
CC BY-SA

**Comment by schrodinstein** [comment]
Attribution-NonCommercial-ShareAlike

**Comment by steph1111** [comment]
Sounds good! Some of my programming friends from the robotics club (we are at an international competition right now) recommended we get a license for this, I will add that one
